import * as React from "react";
import Box from "@mui/material/Box";
import Modal from "@mui/material/Modal";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";

import "./MintResult.css";
const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 500,
  bgcolor: "background.paper",
  // border: "2px solid #000",
  boxShadow: 24,
  pt: 2,
  px: 4,
  pb: 3,
};

interface MintResultProps {
  name: string
  number: number
  open: boolean; // Accept open state as a prop
  isListed: boolean | null;
  setOpen: React.Dispatch<React.SetStateAction<boolean>>; // Accept setOpen as a prop
}

export default function MintResultModal({ name, number, open, isListed, setOpen }: MintResultProps) {
  

  const handleClose = () => {
    setOpen(false);
  };


  return (
    <div>
      <Modal
        open={open}
        onClose={handleClose}
        aria-labelledby="parent-modal-title"
        aria-describedby="parent-modal-description"
      >
        <Box sx={{ ...style, width: 700 }}>
          <Stack spacing={8}>

          <Typography
                component="h1"
                variant="h4"
                sx={{
                  width: "100%",
                  fontSize: "clamp(2rem, 10vw, 1.15rem)",
                  textAlign: "center",
                }}
              >
                🎉You Done It
              </Typography>

            <div>

            
              <p className="description">
                 Congratulations you {isListed ? "minted" : "listed"} {Math.floor(number)} of {name} NFTs that you generated by AI on Linea
              </p>
            </div>
          

           
            <Button variant="contained" color="primary" onClick={handleClose}>
              Close
            </Button>
            </Stack>
        </Box>
      </Modal>
    </div>
  );
}
