import * as React from "react";
import Box from "@mui/material/Box";
import Modal from "@mui/material/Modal";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import TextField from "@mui/material/TextField";
import ButtonGroup from "@mui/material/ButtonGroup";
import MenuItem from "@mui/material/MenuItem";
import "./MintModal.css";
const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 400,
  bgcolor: "background.paper",
  border: "2px solid #000",
  boxShadow: 24,
  pt: 2,
  px: 4,
  pb: 3,
};

interface MintModalProps {
  onSetedMint: (quantity: number, name: string, description: string) => void;
}

const mintNumber = [
  {
    value: "1",
    label: "1",
  },
  {
    value: "10",
    label: "10",
  },
  {
    value: "50",
    label: "50",
  },
  {
    value: "100",
    label: "100",
  },
];

export default function MintModal({ onSetedMint }: MintModalProps) {
  const [open, setOpen] = React.useState(false);
  var [value, setValue] = React.useState(1);
  const [name, setName] = React.useState<string>("");
  const [description, setDescription] = React.useState<string>("");
  const handleOpen = () => {
    setOpen(true);
  };
  const handleClose = () => {
    setOpen(false);
  };

  const handleIncrease = () => {
    if (value <= 99) {
      setValue(value + 1);
    }
  };

  const handleDecrease = () => {
    if (value >= 1) {
      setValue(value - 1);
    }
  };

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setValue(Number(event.target.value));
  };

  const submit = () => {
    console.log(value + " " + name + " " + description )
    onSetedMint(value, name, description);
    handleClose();
  };

  return (
    <div>
      <Button
        variant="contained"
        color="secondary"
        onClick={handleOpen}
        sx={{ width: 205 }}
      >
        {" "}
        Mint NFT
      </Button>
      <Modal
        open={open}
        onClose={handleClose}
        aria-labelledby="parent-modal-title"
        aria-describedby="parent-modal-description"
      >
        <Box sx={{ ...style, width: 500 }}>
          <Stack spacing={8}>
            <div>
              <Typography
                component="h1"
                variant="h4"
                sx={{
                  width: "100%",
                  fontSize: "clamp(2rem, 10vw, 1.15rem)",
                  textAlign: "center",
                }}
              >
                Mint NFT
              </Typography>

              <p className="description">
                {" "}
                Mint the NFT that you generated by AI on Linea
              </p>
            </div>

            <Stack spacing={2} direction="row">
              <TextField
                id="outlined-basic"
                label="NFT name"
                variant="outlined"
                onChange={(e) => setName(e.target.value)}
              />
              <TextField
                id="outlined-basic"
                label="NFT description"
                variant="outlined"
                onChange={(e) => setDescription(e.target.value)}
              />
            </Stack>
            <Stack
              spacing={2}
              direction="row"
              sx={{ justifyContent: "space-between" }}
            >
              <TextField
                id="outlined-select-currency"
                select
                label="Please select NFT number"
                defaultValue="1"
                sx={{ width: 200 }}
                onChange={handleChange}
              >
                {mintNumber.map((option) => (
                  <MenuItem key={option.value} value={option.value}>
                    {option.label}
                  </MenuItem>
                ))}
              </TextField>

              <TextField
                required
                value={value}
                sx={{
                  width: 50,
                  fontSize: "clamp(2rem, 10vw, 2.15rem)",
                  textAlign: "center",
                }}
              />
              <ButtonGroup variant="outlined" aria-label="Basic button group">
                <Button onClick={handleDecrease}>-</Button>
                <Button onClick={handleIncrease}>+</Button>
              </ButtonGroup>
            </Stack>

            <Button variant="contained" color="primary" onClick={submit}>
              Mint
            </Button>
          </Stack>
        </Box>
      </Modal>
    </div>
  );
}
